spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: lb:\\order-service
              predicates:
                - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 9898