spring:
    datasource:
        password: 123456
        url: jdbc:postgresql://localhost:5432/order_domain
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB

server:
    port:8081

springdoc:
    swagger-ui:
        path: /swagger-ui-custom.html